baseURL = 'https://www.jeudijelefais-72.fr/'
languageCode = 'fr-FR'
title = 'Jeudi je le fais'
theme = 'ananke'
defaultContentLanguage = "fr"
sectionPagesMenu = 'main'

[params]
    custom_css = ["css/main.css"]
    azureAppInsightsKey = "0e4b7750-fc3a-4d6e-bb49-c832358ea13d"
