baseURL = 'https://www.jeudijelefais-72.fr/'
languageCode = 'fr-FR'
title = 'Jeudi je le fais'
theme = 'ananke'
defaultContentLanguage = "fr"
sectionPagesMenu = 'main'

[params]
    custom_css = ["css/main.css"]
